name: Publish to NPM

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Build Package
        run: |
          npm ci
          npm run build
          npm run build:module
          rm -rf .github docs example src tests .editorconfig eslint.config.js .gitignore CHANGELOG.md jest.config.js jest.setup.js renovate.json tsconfig.json tsconfig.module.json typedoc.js webpack.config.js package.json-e
          sed -i -e 's/npm --prefix .\/example ci//g' package.json

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}
