name: Version

on:
  push:
    branches:
    - main

permissions:
  id-token: write

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Bump version and update
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Build Package
        run: |
          npm ci
          npm run version:update
