name: Version

on:
  push:
    branches:
    - main

permissions:
  contents: write
  id-token: write

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Update version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm ci
          npm run version:update
          git push origin main
